### ISSUE TITLE
Game gets exception when round is over and a new one never starts

### ISSUE THREAD

**Issue by KarlOfDuty** [Remyk1/Survival-Games#5]
**Describe the bug**
Error when resetting arena, causes the join sign to stay in resetting mode for ever and the next round never starting.

**Errors**
![image](https://user-images.githubusercontent.com/18099825/58914926-10149b80-8720-11e9-88fd-abedb934a9e7.png)

**Specfiy which versions your using**
 - Plugin version: 7.0.3
 - Spigot version: Paper 624
 - WorldEdit version: Fawe 1.13.135

**Additional context**

**Comment by Remyk1** [comment]
Have been able to reproduce this error and it seems to be caused by a jukebox getting the wrong blockdata.

**Comment by KarlOfDuty** [comment]
👍

**Comment by Remyk1** [comment]
As i have alot of work to-do for school it might take a while to fix this one.
Until then i recommend that you remove all the jukeboxes for your arenas.

**Comment by Remyk1** [comment]
Do you need the jukeboxes to play music or are they just decorative?

**Comment by KarlOfDuty** [comment]
Just decorative.
